handle: alexshao
lang: c++
language:
    c:
        codefile: dew.c
        compilecommand: gcc $codefile -o cat
        iscompilelang: true
        name: GNU GCC C11 5.1.0
        programtypeid: "43"
        runcommand: ./cat
    c++:
        codefile: dew.cpp
        compilecommand: g++ $codefile -o cat
        iscompilelang: true
        name: GNU G++17 9.2.0 (64 bit, msys 2)
        programtypeid: "61"
        runcommand: ./cat
    c++17:
        codefile: dew.cpp
        compilecommand: g++ $codefile -o cat -std=c++17
        iscompilelang: true
        name: GNU G++17 7.3.0
        programtypeid: "54"
        runcommand: ./cat
    go:
        codefile: dew.go
        compilecommand: go build -o cat $codefile
        iscompilelang: true
        name: Go 1.19
        programtypeid: "32"
        runcommand: ./cat
    python3:
        codefile: dew.py
        compilecommand: ' '
        iscompilelang: false
        name: Python 3.8.10
        programtypeid: "31"
        runcommand: python3 $codefile
password: asfpoiasfpoi
race: "2024"
rating: 981
